version: '3'
services:
  db:
    image: 'mysql:8.3'
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      - MYSQL_DATABASE=yat
      - MYSQL_USER=nest
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  backend:
    build: ./backend
    ports:
      - ${BACKEND_PORT}:5000
    environment:
      - DATABASE_URL=mysql://nest:${MYSQL_ROOT_PASSWORD}@db:3306/yat
      - JWT_SECRET=${JWT_SECRET}

  frontend:
    build: ./frontend
    ports:
      - ${FRONTEND_PORT}:80
    environment:
      - VITE_BACKEND_URL=${BACKEND_URL}
      - VITE_WS_BACKEND_URL=${WS_BACKEND_URL}
      - VITE_FRONTEND_URL=${FRONTEND_URL}