name: Build Docker Images

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        input:
          -
            images: |
              felipesilvestredev/yat-backend
              ghcr.io/felipecavichiollisilvestre/yat-backend
            folder: backend
          - images: |
              felipesilvestredev/yat-frontend
              ghcr.io/felipecavichiollisilvestre/yat-frontend
            folder: frontend
    steps:
      -
        name: Add Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.input.images }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          context: "{{ defaultContext }}:${{ matrix.input.folder }}"
